version: "3.8"
services:
    front:
        build: ./front
        ports:
            - 5030:5030
        volumes:
            - ./front:/app
        command: ["sh", "-c", "PORT=5030 npm start"]
    back:
        build: ./back
        ports:
        - 8000:8000
        volumes: 
        - ./back:/app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload