version: "3.8"
services:
    back:
        build: ./back
        ports:
            - 8000:8000
        volumes:
            - ./back:/app
        command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    front:
        build: ./front
        ports:
            - 3000:3000
        volumes:
            - ./front:/app
        command: npm start